### ISSUE TITLE
大佬，可以加您联系方式请教一下在sgx中使用eigen的问题吗

### ISSUE THREAD

**Issue by Karssadin** [lcc1999/sgx-dnn#1]

**Comment by lcc1999** [comment]
抱歉，我很久没做相关的东西了，未必能解答你的问题。我更新了代码，你可以自己进行测试。测试时要将slalom中Include文件夹复制到当前目录下，然后export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/lib/gcc/x86_64-linux-gnu/9/include导入部分头文件，make编译动态库，另外我的tensorflow版本为2.5。

**Comment by Karssadin** [comment]
> 抱歉，我很久没做相关的东西了，未必能解答你的问题。我更新了代码，你可以自己进行测试。测试时要将slalom中Include文件夹复制到当前目录下，然后export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/lib/gcc/x86_64-linux-gnu/9/include导入部分头文件，make编译动态库，另外我的tensorflow版本为2.5。

好的，谢谢你，我去试一下。
